services:
  springai-selenide-app:
    build: .
    working_dir: /app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
    networks:
      - app-network
    volumes:
      - ./build/libs/springai-selenide-example-1.0-SNAPSHOT.jar:/app/example-app.jar
    entrypoint: [ "java", "-jar", "/app/example-app.jar" ]

networks:
  app-network: