spring:
  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 1.0
            max-output-tokens: 3000
            thinking-level: HIGH
            internal-tool-execution-enabled: true

telegram:
  bot:
    apiKey: ${TELEGRAM_BOT_API_KEY}